const IDEAS = [
  // === ORIGINAL 50 ===
  // Productive
  "Do 10 pushups right now",
  "Drink a glass of water",
  "Text someone you miss",
  "Learn one keyboard shortcut",
  "Organize your desktop icons",
  "Delete 5 unused apps",
  "Write a haiku about your code",
  "Stretch for 30 seconds",
  "Clean your screen",
  "Update one password",

  // Fun & Games
  "Play one round of Wordle",
  "Do a quick doodle",
  "Watch a 2-min comedy clip",
  "Play rock paper scissors with yourself",
  "Try to touch your toes",
  "Spin in your chair",
  "Make a paper airplane",
  "Do your best robot impression",
  "Practice your signature",
  "See how long you can balance on one foot",

  // Meta & Quirky
  "Spin up another Claude agent",
  "Stare at the loading dots meaningfully",
  "Contemplate the nature of waiting",
  "Wonder if Claude is thinking about you",
  "Appreciate how far AI has come",
  "Think about what you'll automate next",
  "Plan world domination (ethically)",
  "Imagine Claude debugging your life",
  "Ponder: is Claude procrastinating too?",
  "Thank the servers silently",

  // Self-care
  "Take 3 deep breaths",
  "Look at something 20 feet away",
  "Roll your shoulders back",
  "Unclench your jaw",
  "Fix your posture right now",
  "Blink slowly 5 times",
  "Massage your temples",
  "Wiggle your toes",
  "Smile for no reason",
  "Crack your knuckles satisfyingly",

  // Intriguing
  "Google a random historical event",
  "Look up a word you've never used",
  "Find out what phase the moon is in",
  "Check if any planets are visible tonight",
  "Learn to say hello in a new language",
  "Read one Wikipedia random article",
  "Find out what the #1 song was when you were born",
  "Look up your name's meaning",
  "Discover a new subreddit",
  "Find a new podcast to try",

  // === 150 NEW IDEAS ===

  // More Productivity
  "Archive 10 old emails",
  "Set a timer for your next break",
  "Write tomorrow's top 3 priorities",
  "Unsubscribe from one newsletter",
  "Clear your browser tabs (be brave)",
  "Update your calendar for next week",
  "Review your screen time stats",
  "Backup something important",
  "Star a GitHub repo you've been meaning to",
  "Add a book to your reading list",
  "Check your cloud storage usage",
  "Clean your downloads folder",
  "Update one profile picture",
  "Review your notification settings",
  "Archive old Slack channels",

  // Physical Movement
  "Do 5 jumping jacks",
  "Walk to the nearest window",
  "Do a wall sit for 20 seconds",
  "Stretch your wrists (programmer style)",
  "Stand up and sit back down 5 times",
  "Do neck rotations slowly",
  "Flex every muscle then release",
  "Touch all four walls of your room",
  "Do the YMCA dance",
  "March in place for 30 seconds",
  "Do a dramatic superhero pose",
  "Pretend you're swimming",
  "Do air punches like a boxer",
  "Shake out your whole body",
  "Twist side to side like a washing machine",

  // Creative & Silly
  "Draw your mood as a weather icon",
  "Rename a folder something ridiculous",
  "Write a one-sentence short story",
  "Make up a word and define it",
  "Design a logo using only text characters",
  "Compose a jingle for your project",
  "Draw a self-portrait with your eyes closed",
  "Create an acronym from your name",
  "Invent a new pizza topping combo",
  "Name an imaginary band",
  "Design your dream house in your head",
  "Make up a superhero alter ego",
  "Write a limerick about debugging",
  "Doodle a monster on a sticky note",
  "Choreograph a 3-second dance move",

  // More Meta & AI-Related
  "Wonder how many tokens that took",
  "Appreciate the GPU working for you",
  "Think about what Claude is thinking",
  "Consider the philosophical implications",
  "Imagine explaining this to someone in 1990",
  "Marvel at the magic of autocomplete",
  "Ponder the meaning of 'context window'",
  "Wonder if AI dreams of electric code",
  "Appreciate your internet connection",
  "Think about all the training data",
  "Consider becoming a prompt engineer",
  "Imagine AI explaining your code to you",
  "Wonder what the next model will do",
  "Appreciate the humans who made this possible",
  "Think about your great-grandchildren using AI",

  // Food & Drink
  "Refill your water bottle",
  "Think about what you'll eat next",
  "Plan a fancy meal for this weekend",
  "Remember the last great meal you had",
  "Decide on a new recipe to try",
  "Rate your current snack game (1-10)",
  "Contemplate the perfect sandwich",
  "Think about breakfast tomorrow",
  "Consider making a smoothie",
  "Plan a picnic (even a solo one)",
  "Remember a childhood favorite food",
  "Discover a new restaurant nearby",
  "Think about your coffee-to-code ratio",
  "Plan a themed dinner night",
  "Consider meal prepping this Sunday",

  // Social & Connection
  "Send a meme to a friend",
  "Like someone's old post (respectfully)",
  "Think of 3 people you're grateful for",
  "Plan a call with someone you miss",
  "Write a kind DM to someone",
  "Remember a funny inside joke",
  "Think about your next hangout",
  "Send a voice message instead of text",
  "Plan a surprise for someone",
  "Remember a mentor who helped you",
  "Think of someone to introduce to each other",
  "Consider joining an online community",
  "Remember your best collaboration",
  "Think about reconnecting with an old friend",
  "Appreciate your current teammates",

  // Learning & Growth
  "Look up one Git command you've never used",
  "Learn what an obscure HTTP status code means",
  "Read one paragraph of documentation",
  "Watch the first minute of a tutorial",
  "Learn a fun fact about your tech stack",
  "Discover what's new in your language's latest version",
  "Read about a design pattern",
  "Look up a famous computer scientist",
  "Learn what CQRS stands for",
  "Discover a VS Code extension",
  "Read about an architecture you don't use",
  "Learn about a database you've never tried",
  "Look up the history of a programming language",
  "Discover a new CLI tool",
  "Learn what those ESLint rules actually mean",

  // Entertainment & Media
  "Add a movie to your watchlist",
  "Remember your favorite childhood show",
  "Think about the last book that moved you",
  "Queue up a song for later",
  "Remember a concert you loved",
  "Think about your all-time favorite album",
  "Consider starting that series everyone talks about",
  "Remember a quote from a movie",
  "Think about a documentary to watch",
  "Add a video game to your backlog",
  "Remember your first favorite song",
  "Consider revisiting a classic",
  "Think about a podcast episode that stuck with you",
  "Plan a movie marathon theme",
  "Remember a YouTube video that made you laugh",

  // Mindfulness & Reflection
  "Notice 5 things you can see right now",
  "Listen for the furthest sound you can hear",
  "Feel the texture of something nearby",
  "Notice your breathing pattern",
  "Think of one thing that went well today",
  "Acknowledge one challenge you overcame",
  "Set an intention for the rest of today",
  "Recall a moment of pure joy",
  "Appreciate something ordinary",
  "Notice the temperature of the air",
  "Be present for exactly 10 seconds",
  "Acknowledge how far you've come",
  "Think about what younger you would think",
  "Notice something beautiful nearby",
  "Feel grateful for something small",

  // Quirky Challenges
  "Hold your breath for 15 seconds",
  "Say the alphabet backwards in your head",
  "Count all the blue things you can see",
  "Think of 5 words that rhyme with 'code'",
  "Name all the countries starting with 'M'",
  "Recite the months backwards",
  "Count to 100 by 7s",
  "Name 10 fruits as fast as you can",
  "Think of a word for each letter of your name",
  "List all the US states you can remember",
  "Name 5 things in your fridge right now",
  "Think of 3 songs with colors in the title",
  "Name as many dog breeds as you can",
  "List every programming language you know",
  "Think of a food for every letter A-Z",

  // Future Planning
  "Add something to your bucket list",
  "Think about where you'll be in 5 years",
  "Plan a small adventure for next month",
  "Consider learning a musical instrument",
  "Think about a side project idea",
  "Plan a digital detox day",
  "Consider a skill you want to master",
  "Think about a habit to build",
  "Plan a creative project",
  "Consider where you'd like to travel",
  "Think about a fear you want to overcome",
  "Plan something spontaneous",
  "Consider a new hobby to try",
  "Think about a goal for next quarter",
  "Plan a random act of kindness",

  // Nostalgic & Reflective
  "Remember your first computer",
  "Think about your first line of code",
  "Remember a teacher who inspired you",
  "Think about your childhood dream job",
  "Remember your first internet experience",
  "Think about the device you're nostalgic for",
  "Remember an old online username",
  "Think about a trend you miss",
  "Remember your first email address",
  "Think about how you got into tech",
  "Remember a game that defined your childhood",
  "Think about your first phone",
  "Remember a website that no longer exists",
  "Think about the first app you ever made",
  "Remember the first bug you ever fixed"
];
